export const hobbiesList = [
  {id: 1, title: 'Writing', status: false},
  {id: 2, title: 'Cooking', status: false},
  {id: 3, title: 'Singing', status: false},
  {id: 4, title: 'Photography', status: false},
  {id: 5, title: 'Playing instruments', status: false},
  {id: 6, title: 'Painting', status: false},
  {id: 7, title: 'DIY crafts', status: false},
  {id: 8, title: 'Dancing', status: false},
  {id: 9, title: 'Acting', status: false},
  {id: 10, title: 'Poetry', status: false},
  {id: 11, title: 'Gardening', status: false},
  {id: 12, title: 'Blogging', status: false},
  {id: 13, title: 'Content creation', status: false},
  {id: 14, title: 'Designing', status: false},
  {id: 15, title: 'Doodling', status: false},
  {id: 16, title: 'Movies', status: false},
  {id: 17, title: 'Music', status: false},
  {id: 18, title: 'Travelling', status: false},
  {id: 19, title: 'Reading', status: false},
  {id: 20, title: 'Sports', status: false},
  {id: 21, title: 'Social media', status: false},
  {id: 22, title: 'Gaming', status: false},
  {id: 23, title: 'Biking', status: false},
  {id: 24, title: 'Clubbing', status: false},
  {id: 25, title: 'Shopping', status: false},
  {id: 26, title: 'Theatre & Events', status: false},
  {id: 27, title: 'Stand ups', status: false},
  {id: 28, title: 'Running', status: false},
  {id: 29, title: 'Cycling', status: false},
  {id: 30, title: 'Yoga & Meditation', status: false},
  {id: 31, title: 'Walking', status: false},
  {id: 32, title: 'Working out', status: false},
  {id: 33, title: 'Trekking', status: false},
  {id: 34, title: 'Aerobics/Zumba', status: false},
  {id: 35, title: 'Swimming', status: false},
  {id: 36, title: 'Pets', status: false},
  {id: 37, title: 'Foodie', status: false},
  {id: 38, title: 'Vegan', status: false},
  {id: 39, title: 'News & Politics', status: false},
  {id: 40, title: 'Social service', status: false},
  {id: 41, title: 'Entrepreneurship', status: false},
  {id: 42, title: 'Home decor', status: false},
  {id: 43, title: 'Investments', status: false},
  {id: 44, title: 'Fashion & beauty', status: false},
];
